# ==============================================================================
# TIME-COURSE DIFFERENTIAL EXPRESSION ANALYSIS WITH DESeq2 (TEMPLATE)
# ==============================================================================
# Purpose: Identify genes with significant temporal dynamics using LRT
# Status: TEMPLATE - Aligned with pilot-analysis directory structure
# Requirements: DESeq2, ggplot2, tidyverse, pheatmap, BiocParallel
# ==============================================================================

library(DESeq2)
library(ggplot2)
library(tidyverse)
library(pheatmap)
library(BiocParallel)

message("==================================================")
message("TIME-COURSE DIFFERENTIAL EXPRESSION ANALYSIS")
message("==================================================")

# ==============================================================================
# 1. LOAD COUNT DATA & METADATA
# ==============================================================================

message("[STEP 1] Loading count matrices...")

count_file <- "./pilot-analysis/processed_data/gene_counts/host_counts.txt"

if (!file.exists(count_file)) {
  stop("[ERROR] Count file not found at: ", count_file, "\nPlease run alignment/quantification first.")
}

# Skip the first comment line generated by featureCounts (# Program:featureCounts...)
raw_counts <- read.table(count_file, header = TRUE, row.names = 1, skip = 1, check.names = FALSE)

# Because row.names=1 consumed column 1 (Geneid), columns 1-5 of raw_counts are metadata (Chr, Start, etc.)
# Actual numeric sample counts begin at column 6.
count_matrix <- raw_counts[, 6:ncol(raw_counts), drop = FALSE]

# Clean up column names (strip file path and alignment suffix)
colnames(count_matrix) <- basename(colnames(count_matrix)) %>% 
  str_remove(".sorted.bam")

message(paste("[INFO] Loaded count matrix:", nrow(count_matrix), "genes x", ncol(count_matrix), "samples"))

# ==============================================================================
# 2. LOAD OR GENERATE SAMPLE METADATA
# ==============================================================================

message("[STEP 2] Structuring sample metadata...")

# Programmatically parse timepoints and replicates from cleaned column names
sample_names <- colnames(count_matrix)

timepoints <- str_extract(sample_names, "\\d+(?=(hpi|h|_h))") %>% 
  replace_na("0") %>% 
  as.numeric()

replicates <- str_extract(sample_names, "(rep|r)\\d+") %>% 
  str_extract("\\d+") %>% 
  replace_na("1") %>% 
  as.numeric()

metadata <- data.frame(
  sample_name = sample_names,
  timepoint   = as.factor(timepoints), # Treated as factor for LRT
  replicate   = as.factor(replicates),
  row.names   = sample_names
)

message("[INFO] Formatted Metadata:")
print(metadata)

# ==============================================================================
# 3. BUILD DESEQ2 OBJECT
# ==============================================================================

message("[STEP 3] Building DESeq2 object...")

count_matrix <- count_matrix[, rownames(metadata), drop = FALSE]

# Note: In presence of batch effects, use: design = ~ batch + timepoint
dds <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData   = metadata,
  design    = ~ timepoint
)

# Safely register multi-threading
register(MulticoreParam(workers = 4))

# ==============================================================================
# 4. FILTERING: REMOVE LOW-COUNT GENES
# ==============================================================================

message("[STEP 4] Filtering low-abundance genes...")

# Retain genes with >= 10 reads in at least 3 samples (size of one biological group)
keep <- rowSums(counts(dds) >= 10) >= 3
dds  <- dds[keep, ]

message(paste("[INFO] Retained", nrow(dds), "genes after filtering"))

# ==============================================================================
# 5. LIKELIHOOD RATIO TEST (LRT) FOR TIME-COURSE DATA
# ==============================================================================

message("[STEP 5] Performing Likelihood Ratio Test (LRT)...")

# Full model: expression changes across timepoints
# Reduced model: expression remains constant (~ 1)
dds <- DESeq(dds, test = "LRT", reduced = ~ 1, parallel = TRUE)

message("[INFO] DESeq2 model fitting complete")

# ==============================================================================
# 6. EXTRACT & ORGANIZE RESULTS
# ==============================================================================

message("[STEP 6] Extracting temporal results...")

res <- results(dds)
res$gene_name <- rownames(res)
res_sorted <- res[order(res$padj), ]

# Statistical threshold: FDR < 0.05
sig_genes <- subset(res_sorted, padj < 0.05)
num_sig <- nrow(sig_genes)

message(paste("[INFO] Found", num_sig, "genes with significant temporal dynamics (padj < 0.05)"))

# ==============================================================================
# 7. EXPLORE TEMPORAL PATTERNS
# ==============================================================================

message("[STEP 7] Extracting normalized temporal expression patterns...")

norm_counts <- counts(dds, normalized = TRUE)

if (num_sig > 0) {
  top_genes <- rownames(sig_genes)[1:min(20, num_sig)]
  
  count_summary <- norm_counts[top_genes, , drop = FALSE] %>%
    as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    pivot_longer(-gene_id, names_to = "sample", values_to = "normalized_count") %>%
    left_join(metadata %>% rownames_to_column("sample"), by = "sample")
}

# ==============================================================================
# 8. VISUALIZATIONS
# ==============================================================================

message("[STEP 8] Creating visualizations...")

plots_dir <- "./pilot-analysis/processed_data/plots"
dir.create(plots_dir, showWarnings = FALSE, recursive = TRUE)

if (num_sig >= 10) {
  heatmap_genes <- rownames(sig_genes)[1:min(50, num_sig)]
  heatmap_matrix <- norm_counts[heatmap_genes, , drop = FALSE]
  
  # CRITICAL: Filter out any zero-variance genes to prevent pheatmap clustering crashes
  gene_variances <- apply(heatmap_matrix, 1, var)
  heatmap_matrix_filtered <- heatmap_matrix[gene_variances > 0, , drop = FALSE]
  
  if (nrow(heatmap_matrix_filtered) >= 2) {
    png(file.path(plots_dir, "temporal_heatmap.png"), width = 800, height = 1000, res = 120)
    pheatmap(
      heatmap_matrix_filtered,
      main = "Top Temporally-Regulated Genes (Z-Score Scaled)",
      color = colorRampPalette(c("blue", "white", "red"))(100),
      scale = "row",
      clustering_method = "ward.D2",
      show_rownames = FALSE
    )
    dev.off()
    message("[SUCCESS] Heatmap saved: temporal_heatmap.png")
  } else {
    message("[WARNING] Insufficient variance in top genes to generate a heatmap.")
  }
}

if (num_sig > 0) {
  # Plot temporal trajectory of top 6 genes
  p_line <- ggplot(count_summary %>% filter(gene_id %in% top_genes[1:min(6, num_sig)]), 
                   aes(x = timepoint, y = normalized_count, color = gene_id, group = gene_id)) +
    geom_line(linewidth = 1) +
    geom_point(size = 2.5) +
    facet_wrap(~gene_id, scales = "free_y") +
    theme_bw() +
    labs(
      title = "Temporal Gene Expression Dynamics (Top 6 Genes)",
      x = "Hours Post-Infection (hpi)", 
      y = "Normalized Counts"
    ) +
    theme(legend.position = "none")
  
  ggsave(file.path(plots_dir, "temporal_dynamics.png"), plot = p_line, width = 10, height = 6)
  message("[SUCCESS] Line plot saved: temporal_dynamics.png")
}

# ==============================================================================
# 9. SAVE OUTPUT FILES
# ==============================================================================

message("[STEP 9] Saving results...")

results_dir <- "./pilot-analysis/processed_data/results"
dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)

write.csv(as.data.frame(res_sorted), file = file.path(results_dir, "all_genes_deseq2_results.csv"), row.names = TRUE)
write.csv(norm_counts, file = file.path(results_dir, "normalized_counts.csv"), row.names = TRUE)

if (num_sig > 0) {
  write.csv(as.data.frame(sig_genes), file = file.path(results_dir, "temporal_degs.csv"), row.names = TRUE)
}

message("[SUCCESS] Output files successfully exported to:", results_dir)
message("==================================================")
